<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Age_group extends MY_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Age_group_model');
    } 

    /*
     * Listing of age_groups
     */
    function index()
    {		
		if( $this->require_role('admin') )
			{
        $data['age_groups'] = $this->Age_group_model->get_all_age_groups();
        
        $data['_view'] = 'age_group/index';
        $this->load->view('mainpage',$data);
			}
    }

    /*
     * Adding a new age_group
     */
    function add()
    {   
			if( $this->require_role('admin') )
			{
        $this->load->library('form_validation');

				$this->form_validation->set_rules('age_group_name','Age Group Name','max_length[100]');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'age_group_name' => $this->input->post('age_group_name'),
            );
            
            $age_group_id = $this->Age_group_model->add_age_group($params);
            redirect('age_group/index');
        }
        else
        {            
            $data['_view'] = 'age_group/add';
            $this->load->view('mainpage',$data);
        }
			}
    }  

    /*
     * Editing a age_group
     */
    function edit($age_group_id)
    {   
			if( $this->require_role('admin') )
			{
        // check if the age_group exists before trying to edit it
        $data['age_group'] = $this->Age_group_model->get_age_group($age_group_id);
        
        if(isset($data['age_group']['age_group_id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('age_group_name','Age Group Name','max_length[100]');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'age_group_name' => $this->input->post('age_group_name'),
                );

                $this->Age_group_model->update_age_group($age_group_id,$params);            
                redirect('age_group/index');
            }
            else
            {
                $data['_view'] = 'age_group/edit';
                $this->load->view('mainpage',$data);
            }
        }
        else
            show_error('The age_group you are trying to edit does not exist.');
			}
    } 

    /*
     * Deleting age_group
     */
    function remove($age_group_id)
    {
			if( $this->require_role('admin') )
			{
        $age_group = $this->Age_group_model->get_age_group($age_group_id);

        // check if the age_group exists before trying to delete it
        if(isset($age_group['age_group_id']))
        {
            $this->Age_group_model->delete_age_group($age_group_id);
            redirect('age_group/index');
        }
        else
            show_error('The age_group you are trying to delete does not exist.');
			}
    }
    
}
