<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Event_type extends MY_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Event_type_model');
    } 

    /*
     * Listing of event_types
     */
    function index()
    {
        $data['event_types'] = $this->Event_type_model->get_all_event_types();
        
        $data['_view'] = 'event_type/index';
        $this->load->view('mainpage',$data);
    }

    /*
     * Adding a new event_type
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'event_type' => $this->input->post('event_type'),
            );
            
            $event_type_id = $this->Event_type_model->add_event_type($params);
            redirect('event_type/index');
        }
        else
        {            
            $data['_view'] = 'event_type/add';
            $this->load->view('mainpage',$data);
        }
    }  

    /*
     * Editing a event_type
     */
    function edit($event_type_id)
    {   
        // check if the event_type exists before trying to edit it
        $data['event_type'] = $this->Event_type_model->get_event_type($event_type_id);
        
        if(isset($data['event_type']['event_type_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'event_type' => $this->input->post('event_type'),
                );

                $this->Event_type_model->update_event_type($event_type_id,$params);            
                redirect('event_type/index');
            }
            else
            {
                $data['_view'] = 'event_type/edit';
                $this->load->view('mainpage',$data);
            }
        }
        else
            show_error('The event_type you are trying to edit does not exist.');
    } 

    /*
     * Deleting event_type
     */
    function remove($event_type_id)
    {
        $event_type = $this->Event_type_model->get_event_type($event_type_id);

        // check if the event_type exists before trying to delete it
        if(isset($event_type['event_type_id']))
        {
            $this->Event_type_model->delete_event_type($event_type_id);
            redirect('event_type/index');
        }
        else
            show_error('The event_type you are trying to delete does not exist.');
    }
    
}
