<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Event_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get event by event_id
     */
    function get_event($event_id)
    {
        return $this->db->get_where('cia12_events',array('event_id'=>$event_id))->row_array();
    }
        
    /*
     * Get all events
     */
    function get_all_events()
    {
        $this->db->order_by('event_id', 'desc');
        return $this->db->get('cia12_events')->result_array();
    }
        
    /*
     * function to add new event
     */
    function add_event($params)
    {
        $this->db->insert('cia12_events',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update event
     */
    function update_event($event_id,$params)
    {
        $this->db->where('event_id',$event_id);
        return $this->db->update('cia12_events',$params);
    }
    
    /*
     * function to delete event
     */
    function delete_event($event_id)
    {
        return $this->db->delete('cia12_events',array('event_id'=>$event_id));
    }
}
