<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Event_person_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get event_person by id
     */
    function get_event_person($id)
    {
        return $this->db->get_where('cia12_event_people',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all event_people
     */
    function get_all_event_people()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('cia12_event_people')->result_array();
    }
        
    /*
     * function to add new event_person
     */
    function add_event_person($params)
    {
        $this->db->insert('cia12_event_people',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update event_person
     */
    function update_event_person($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('cia12_event_people',$params);
    }
    
    /*
     * function to delete event_person
     */
    function delete_event_person($id)
    {
        return $this->db->delete('cia12_event_people',array('id'=>$id));
    }
}
