<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Event_person_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
		
		function get_events_by_people_id($people_id)
		{
			$this->db->select('cia12_events.event_id, event_name, date, location, cia12_event_type.event_type, attended, registered, paid');
			$this->db->from('cia12_events, cia12_event_type,cia12_event_people');
			$this->db->where('cia12_events.event_type_id = cia12_event_type.event_type_id');
			$this->db->where('cia12_events.event_id = cia12_event_people.event_id');
			$this->db->where('people_id', $people_id);
			$query = $this->db->get();
			return $query->result_array();	
		}
		
    /*
     * Get event_person by id
     */
    function get_event_person($event_people_id)
    {
        return $this->db->get_where('cia12_event_people',array('event_people_id'=>$event_people_id))->row_array();
    }
		
    /*
     * Get event_person by event_id
     */
    function get_event_person_by_event_id($event_id)
    {
			$this->db->select('event_people_id, cia12_event_people.people_id, CONCAT(cia12_people.first_name, " ", cia12_people.last_name) AS full_name, cia12_events.event_name, registered, attended, paid, comment');
			$this->db->from('cia12_event_people, cia12_events, cia12_people, cia12_halls');
			$this->db->where('cia12_event_people.people_id = cia12_people.people_id');
			$this->db->where('cia12_event_people.event_id', $event_id);
			$this->db->where('cia12_event_people.event_id = cia12_events.event_id');
			$this->db->where('cia12_events.hall_id = cia12_halls.hall_id');
			$query = $this->db->get();
			return $query->result_array();	
    }  

    /*
     * Get event_person by event_id
     */
    function get_event_person_by_person_id($person_id)
    {
			$this->db->select('event_people_id, cia12_event_people.people_id, CONCAT(cia12_people.first_name, " ", cia12_people.last_name) AS full_name, cia12_events.event_name, registered, attended, paid, comment');
			$this->db->from('cia12_event_people, cia12_events, cia12_people, cia12_halls');
			$this->db->where('cia12_event_people.people_id', $person_id);
			$this->db->where('cia12_event_people.people_id = cia12_people.people_id');
			$this->db->where('cia12_event_people.event_id = cia12_events.event_id');
			$this->db->where('cia12_events.hall_id = cia12_halls.hall_id');
			$query = $this->db->get();
			return $query->result_array();	
    } 		
		
    /*
     * Get all event_people
     */
    function get_all_event_people()
    {
			$this->db->select('event_people_id, CONCAT(cia12_people.first_name, " ", cia12_people.last_name) AS full_name, cia12_events.event_name, registered, attended, paid, comment');
			$this->db->from('cia12_event_people, cia12_events, cia12_people, cia12_halls');
			$this->db->where('cia12_event_people.people_id = cia12_people.people_id');
			$this->db->where('cia12_event_people.event_id = cia12_events.event_id');
			$this->db->where('cia12_events.hall_id = cia12_halls.hall_id');
			$query = $this->db->get();
			return $query->result_array();
    }
        
    /*
     * function to add new event_person
     */
    function add_event_person($params)
    {
        $this->db->insert('cia12_event_people',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update event_person
     */
    function update_event_person($id,$params)
    {
        $this->db->where('event_people_id',$id);
        return $this->db->update('cia12_event_people',$params);
    }
    
    /*
     * function to delete event_person
     */
    function delete_event_person($id)
    {
        return $this->db->delete('cia12_event_people',array('event_people_id'=>$id));
    }
}
