<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Event_type_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get event_type by event_type_id
     */
    function get_event_type($event_type_id)
    {
        return $this->db->get_where('cia12_event_type',array('event_type_id'=>$event_type_id))->row();
    }
        
    /*
     * Get all event_types
     */
    function get_all_event_types()
    {
        $this->db->order_by('event_type_id', 'desc');
        return $this->db->get('cia12_event_type')->result_array();
    }
        
    /*
     * function to add new event_type
     */
    function add_event_type($params)
    {
        $this->db->insert('cia12_event_type',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update event_type
     */
    function update_event_type($event_type_id,$params)
    {
        $this->db->where('event_type_id',$event_type_id);
        return $this->db->update('cia12_event_type',$params);
    }
    
    /*
     * function to delete event_type
     */
    function delete_event_type($event_type_id)
    {
        return $this->db->delete('cia12_event_type',array('event_type_id'=>$event_type_id));
    }
}
