<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Event_person_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get event_person by id
     */
    function get_event_person($event_people_id)
    {
        return $this->db->get_where('cia12_event_people',array('event_people_id'=>$event_people_id))->row_array();
    }
        
    /*
     * Get all event_people
     */
    function get_all_event_people()
    {
							return $this->db->query('SELECT event_people_id, cia12_people.people_id, cia12_events.event_id, registered, attended, paid, comment
				FROM cia12_event_people, cia12_events, cia12_people, cia12_halls
				WHERE cia12_event_people.people_id = cia12_people.people_id 
				AND cia12_event_people.event_id = cia12_events.event_id
				AND cia12_events.hall_id = cia12_halls.hall_id;')->result_array();
				
    }
        
    /*
     * function to add new event_person
     */
    function add_event_person($params)
    {
        $this->db->insert('cia12_event_people',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update event_person
     */
    function update_event_person($id,$params)
    {
        $this->db->where('event_people_id',$id);
        return $this->db->update('cia12_event_people',$params);
    }
    
    /*
     * function to delete event_person
     */
    function delete_event_person($id)
    {
        return $this->db->delete('cia12_event_people',array('event_people_id'=>$id));
    }
}
