<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Person_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get person by people_id
     */
    function get_person($people_id)
    {
        return $this->db->get_where('cia12_people',array('people_id'=>$people_id))->row_array();
    }
        
    /*
     * Get all people
     */
    function get_all_people()
    {
        $this->db->order_by('people_id', 'desc');
        return $this->db->get('cia12_people')->result_array();
    }
        
    /*
     * function to add new person
     */
    function add_person($params)
    {
        $this->db->insert('cia12_people',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update person
     */
    function update_person($people_id,$params)
    {
        $this->db->where('people_id',$people_id);
        return $this->db->update('cia12_people',$params);
    }
    
    /*
     * function to delete person
     */
    function delete_person($people_id)
    {
        return $this->db->delete('cia12_people',array('people_id'=>$people_id));
    }
}
