<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Person_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
		
		
    /*
     * Get person by people_id
     */
    function get_person($people_id)
    {
        return $this->db->get_where('cia12_people',array('people_id'=>$people_id))->row_array();
    }
    
		function set_hall_id($hall_id)
		{
			$this->db->where('cia12_halls.hall_id', $hall_id);		
		}			
				
		function get_people()
		{
			$this->db->select('people_id, first_name, last_name, gender, age_group_name, email, hall_name, mobile');
			$this->db->from('cia12_people');
			$this->db->from('cia12_age_group');
			$this->db->where('cia12_people.age_group_id = cia12_age_group.age_group_id');	
			$this->db->from('cia12_halls');
			$this->db->where('cia12_people.hall_id = cia12_halls.hall_id');
			$this->db->where('cia12_people.age_group_id = cia12_age_group.age_group_id');

			$query = $this->db->get();
			return $query->result_array();
		}
		
		function set_age_group($age_group_id)
		{
			$this->db->where('cia12_people.age_group_id >', $age_group_id);
			$this->db->where('cia12_people.age_group_id <', $age_group_id + 10);	
		}
		
        
    /*
     * function to add new person
     */
    function add_person($params)
    {
        $this->db->insert('cia12_people',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update person
     */
    function update_person($people_id,$params)
    {
        $this->db->where('people_id',$people_id);
        return $this->db->update('cia12_people',$params);
    }
    
    /*
     * function to delete person
     */
    function delete_person($people_id)
    {
        return $this->db->delete('cia12_people',array('people_id'=>$people_id));
    }
}
