<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class User_profile_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
		function get_by_user_id($user_id)
		{
			$this->db->select('user_profile_id, user_id, people_id, serving_primary, serving_int, serving_hs, serving_campus');
			$this->db->from('cia12_user_profiles');
			$this->db->where('user_id', $user_id);
			
			$query = $this->db->get();
			return $query->row_array();
		}
		
		function get_user($user_id)
		{
			$this->db->select('users.user_id, username, users.email, first_name, last_name, auth_level, serving_primary, serving_int, serving_hs, serving_campus');
			$this->db->from('users, cia12_people, cia12_user_profiles');
			$this->db->where('cia12_people.people_id = cia12_user_profiles.people_id');	
			$this->db->where('users.user_id', $user_id);
			$this->db->where('users.user_id = cia12_user_profiles.user_id');	

			$query = $this->db->get();
			return $query->row_array();
		}
		
		function get_users()
		{
			$this->db->select('users.user_id, username, users.email, first_name, last_name, auth_level, serving_primary, serving_int, serving_hs, serving_campus');
			$this->db->from('users, cia12_people, cia12_user_profiles');
			$this->db->where('cia12_people.people_id = cia12_user_profiles.people_id');	
			$this->db->where('users.user_id = cia12_user_profiles.user_id');	

			$query = $this->db->get();
			return $query->result_array();
		}
		
		function get_user_profile_user_ids()
		{
			$this->db->select('people_id');
			$this->db->from('cia12_user_profiles');

			$query = $this->db->get();
			return $query->result_array();			
		}
		
		function update_user_profile($user_profile_id, $params){
			$this->db->where('user_profile_id', $user_profile_id);
			return $this->db->update('cia12_user_profiles', $params);
		}

    /*
     * function to add new event
     */
    function add_user_profile($params)
    {
        $this->db->insert('cia12_user_profiles',$params);
        return $this->db->insert_id();
    }

    
    /*
     * function to delete person
     */
    function delete_user_profile($user_id)
    {
        return $this->db->delete('cia12_user_profiles',array('user_id'=>$user_id));
    }
}
